//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Budget.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int Departamento { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Expiracion { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
    }
}
